### ISSUE TITLE
Embedded Linux shared library won't work with more conservative Linux distros

### ISSUE THREAD

**Issue by eliaslevy** [cerebuild/hyperscan-java#13]
Conservative Linux distros, such as Amazon Linux, have older versions of gcc/libstdc++.  That leads to an error when JNA tries to load the embedded shared library (`java.lang.UnsatisfiedLinkError: /usr/lib64/libstdc++.so.6: version "GLIBCXX_3.4.20" not found`), which has been compiled with a newer ABI.  As libstdc++ is forward compatible, using versioned symbols, to maximize compatibility, it would be best for the embedded `libhs.so` to be compiled using an older version of gcc/libstdc++.  Then it could be used in older and newer systems.

**Comment by gliwka** [comment]
Nice catch! Seems like not everybody is running Arch Linux ;-)

I'm going to compile it with Centos 5, so it's compatible with RHEL 5 too, which should be the oldest distribution still on an support cycle.

**Comment by gliwka** [comment]
Have to drop RHEL 5 and move up to RHEL/CentOS 6. 

Building it on RHEL/CentOS 5 is a dependency hell disaster.

**Comment by gliwka** [comment]
The new shared library now uses the GLIBCXX_3.4.9 symbols and below and has been published in release 0.4.3. 

@eliaslevy, could you please try again with this version?

**Comment by eliaslevy** [comment]
It works.
