### ISSUE TITLE
Built-in Linux hyperscan shared library fails in Amazon Linux AMI

### ISSUE THREAD

**Issue by eliaslevy** [cerebuild/hyperscan-java#33]
I am not sure what is is about the hyperscan Linux shared library bundled with the jar, but the update in  0.4.10 broke my app in EC2.  Since then `hs_alloc_scratch` returns `HS_DB_VERSION_ERROR` even when passed a database created right before the call.  I built my own `libhs.so` and repackaged the jar and that fixed the issue.

The Linux version is:
```
Linux version 4.4.11-23.53.amzn1.x86_64 (mockbuild@gobi-build-60009) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Wed Jun 1 22:22:50 UTC 2016
```

**Comment by gliwka** [comment]
Thats very strange. I'll look into it. 

Can you verify that a ```mvn test``` fails on the same machine?

**Comment by eliaslevy** [comment]
`mvn test` runs with no errors.

**Comment by gliwka** [comment]
Sorry, got caught in up travel preparations. Will try to take a look at this issue next week when I arrive at my destination. I undestand you found a workaround, so this shouldn't be a blocker.

**Comment by gliwka** [comment]
Not sure why, but I can't reproduce this :-/

**Comment by eliaslevy** [comment]
I upgraded my instances to the latest version of the Amazon Linux AMIs and the problem went away.  Closing.
